### ISSUE TITLE
Xvisor boot on freescale sabre ai/sd board

### ISSUE THREAD

**Issue by devendersys** [xvisor/xvisor#104]
Hi,

I was wondering whether this forum is still under discussion regarding issues, but sharing issue I am facing with sabre ai/sd board.

I am able to build xvisor binary file for sabre ai/sd board using One_guest_sabrelite.dtb file,but I am stuck at starting kernel..... 

Whether i have to change dtb files because it seems xvisor kernel is not booting.

Looking forward for response.
   
Generated log:

==================================================================
U-Boot 2017.03 (Jun 30 2017 - 17:04:47 +0530)

CPU:   Freescale i.MX6Q rev1.2 996 MHz (running at 792 MHz)
CPU:   Automotive temperature grade (-40C to 125C) at 41C
Reset cause: POR
Board: MX6-SabreSD
I2C:   ready
DRAM:  1 GiB
PMIC:  PFUZE100 ID=0x10
MMC:   FSL_SDHC: 0, FSL_SDHC: 1, FSL_SDHC: 2
*** Warning - bad CRC, using default environment

PCI:   pcie phy link never came up
No panel detected: default to Hannstar-XGA
Display: Hannstar-XGA (1024x768)
In:    serial
Out:   serial
Err:   serial
Net:   FEC [PRIME]
Hit any key to stop autoboot:  0
=> setenv board sabrelite
=> seten bootargs console=ttymxc0,115200 earlyprintk root=/dev/mmcblk0p2 rootwait panic=10
=> mmc dev 1:1
switch to partitions #0, OK
mmc1 is current device
=> fatload mmc 1:1 10008000 /6x_bootscript
reading /6x_bootscript
1055 bytes read in 26 ms (39.1 KiB/s)
=> source 10008000
## Executing script at 10008000
Load from SD/MMC
reading /uvmm.bin
1522668 bytes read in 94 ms (15.4 MiB/s)
reading /vmm-imx6q-sabrelite.dtb
16589 bytes read in 19 ms (852.5 KiB/s)
## Booting kernel from Legacy Image at 10800000 ...
   Image Name:   Xvisor
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    1522604 Bytes = 1.5 MiB
   Load Address: 17800000
   Entry Point:  17800000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 12000000
   Booting using the fdt blob at 0x12000000
   Loading Kernel Image ... OK
   reserving fdt memory region: addr=10000000 size=1000
   Using Device Tree in place at 12000000, end 120070cc

Starting kernel ...
===========================================================================

**Comment by avpatel** [comment]
Xvisor is tested on SaberLITE and Nitrogen_6x where the console UART is UART2 while on SaberSD the console UART is UART1.

change "console = &SERIAL2;" to "console = &SERIAL1;" in one_guest_saberlite.dts and re-compile to create and try updated images.

**Comment by devendersys** [comment]
Hello Anup,

Thanks for your reply and providing information.

I tried these changes but I am still stuck at "Starting Kernel" even after changing the parameters as suggested by you.

I also changed the dtsi file as per your xvisor git repository, where I found uart related current changes in imx6q.dtsi file for sabrelite. 

Is it possible that  xvisor's UVVM.bin (which is meant for sabrelite) is not compatible with sabre sd board? Do I need to make changes in defconfig file to make compatible with sabre sd board?

waiting for you reply.

Thanks,
Devender

**Comment by avpatel** [comment]
Hi Devender,

I don't have Saber SD board. The Xvisor i.MX6 support is mostly tested on SaberLITE and Nitrogen_6x boards.

If possible please try on SaberLITE or Nitrogen_6x board.

Meanwhile, I will try to think more ways to debug Saber SD board.

Regards,
Anup

**Comment by devendersys** [comment]
Hi Anup,

Thanks for reply and appreciate your efforts towards resolution for this issue.

I am trying to get SabreLITE board, by the time I get it, I am trying to perform few activities to understand how it be run on sabreSD board.

1. Thoroughly study Xvisor code with respect to SabreLITE board.
2. Understand difference between SabreLITE and SabreSD at hardware and specification level.

Could you please guide me whether I am thinking in right direction or if you can provide some pointers to get the right approach?

Thanks,
Devender

**Comment by avpatel** [comment]
There has been lot of discussions around this on Xvisor-devel. Please refer old email threads on Xvisor-devel google group.

Closing this issue now.

Regards,
Anup
