### ISSUE TITLE
imx6sabresd with xvisor

### ISSUE THREAD

**Issue by lxiaogao** [xvisor/xvisor#105]
hi pater ,I know cortex a9 does not support Virtualization instructions 。how did you realize hypervisor on imx6[cortex a9 inside]。use AMP mode ? or  trustzone mode dula-os ?

**Comment by avpatel** [comment]
We use software technique called instruction patching at compile time and emulate MMU in software using domain protection and access protection.

You can look at Jim Huang's presentation to get some basic idea. Refer https://www.slideshare.net/jserv/xvisor
