### ISSUE TITLE
is there a way to communicate with xvisor from an outside computer?

### ISSUE THREAD

**Issue by CheyenneForbes** [xvisor/xvisor#108]

**Comment by avpatel** [comment]
Yes, it is certainely possible. The Xvisor network packet switching allows dummy vmm_netport instances which can be used by Xvisor to communicate to outside world. We have an optional network stack implemented using lwIP. This lwIP based network stack creates dummy vmm_netport instance which is attached to vmm_netswitch containing vmm_netport instance of host NIC and Guest NICs.

**Comment by CheyenneForbes** [comment]
Thanks for that information but my question was misunderstood.. I meant like an API to do things like creating vms and checking vm cpu usage

**Comment by avpatel** [comment]
Ahh OK. We have been mostly focusing on embedded systems so we never felt the need of creating/managing VMs remotely. Due this, we have required functionality in Xvisor but we don't have remote management APIs. Eventually, we want to have such remote management APIs and support it using Libvirt.

**Comment by CheyenneForbes** [comment]
Could you point me to resources which show how to launch vms? the doxygen site doesnt seem to be properly set up

also how does performance, etc. compare to xen, kvm and vmware?

**Comment by avpatel** [comment]
For ARM64, you can start with Foundation v8 model or RPi3 board.
Refer,
<xvisor_source>/docs/arm/foundation-v8.txt
<xvisor_source>/docs/arm/bcm2837-raspi3.txt

Here's link to Xvisor paper which compare it against KVM and XEN for ARM32 world
http://xhypervisor.org/pdf/Embedded_Hypervisor_Xvisor_A_comparative_analysis.pdf

Few more interesting papers:
http://xhypervisor.org/pdf/Xvisor_VirtIO_CAN_Fast_virtualized_CAN.pdf
http://xhypervisor.org/pdf/dual-ICIT18.pdf
http://xhypervisor.org/pdf/isol-ICIT18.pdf

Regards,
Anup

**Comment by avpatel** [comment]
Closing this issue now.

Regards,
Anup
