### ISSUE TITLE
Stuck at Starting kernel ... 

### ISSUE THREAD

**Issue by wire-mistry** [xvisor/xvisor#111]
Hi, 
I am just trying to boot the binary after failing various tries to boot with dtb. I assume that even if say dtb is not compatible with the binary (though tried after compiling), Binary should be throwing certain messages regarding dtb missing or rootfs/initrd missing but I am not receiving any of such log. Please guide us what is the meaning of this behavior.Below are the spec of board.

A follow-up and architecture based question I have is .. "Is Xvisor is a standalone binary? in other word is it necessary to compile the kernel images with Xvisor to work with? **or** By just executing the Xvisor binary uvmm.bin by bootm  command or vmm.bin by go command is capable of giving us a terminal of Xvisor."

Board Spec:
iMX6QP - 1GB Ram 8GB Customized by adding different more devices on top of it.
Why I am not expecting a odd behavior is because 6x has iMX6Q which is same processor as iMX6QP.

Request you to share your views on same if I have wrong understanding on the same also about the Xvisor binary dependency.
```
Hit any key to stop autoboot:  0
=> usb start && load usb 0 0x17800000 uvmm.bin
starting USB...
USB0:   USB EHCI 1.00
scanning bus 0 for devices... 2 USB Device(s) found
USB1:   USB EHCI 1.00
scanning bus 1 for devices... 1 USB Device(s) found
       scanning usb for storage devices... 1 Storage Device(s) found
reading uvmm.bin
2033528 bytes read in 87 ms (22.3 MiB/s)
=> bootm 17800000
## Booting kernel from Legacy Image at 17800000 ...
   Image Name:   Xvisor
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    2033464 Bytes = 1.9 MiB
   Load Address: 17800000
   Entry Point:  17800000
   Verifying Checksum ... OK
   Loading Kernel Image ... OK

Starting kernel ...
```

**Comment by avpatel** [comment]
There has been lot of discussion related to i.MX6 in past. Please refer old Xvisor-devel email threads on Xvisor-devel google groups.

Please send email to xvisor-devel google group if you have more questions.

Closing this issue now.

Regards,
Anup
