### ISSUE TITLE
I'm curious why firmware.elf.patched is same as firmware.elf ?

### ISSUE THREAD

**Issue by chengshuyi** [xvisor/xvisor#112]
I follow `./docs/arm/imx6-sabrelite.txt` guide to build xvisor and generate firmware. Locating at `.build/tools/cpatch` and `./arch/arm/cpu/arm32/elf2cpatch.py` will patch the `firmware.elf` file when running `make -C tests/arm32/vexpress-a9/basic`. 

After that, I think some sensitive non-priviliged instruction will be replaced by hypercall instruction,  however I run `diff firmware.elf firmware.elf.patched` and ouput nothing. Then i run `arm-linux-gnueabi-objdump` command to objdump that two files and run `diff` command. But still output nothing.

Why is firmware.elf.patched same as firmware.elf ?

Thanks for any advice!

**Comment by avpatel** [comment]
firmware.elf.patched cannot be same as firmware.elf. 

You might have some issue in the way you are building basic firmware.

Please start an email thread on xvisor-devel if you still face issues.

Regards,
Anup
