### ISSUE TITLE
Xvisor on Renesas R-Car H3 Starter Kit

### ISSUE THREAD

**Issue by nadeemathani** [xvisor/xvisor#113]
Hello Sir,

Requesting to provide any doc. for porting xvisor on rcar h3 starter kit.
Is this doc. zynqmp-zcu102.txt will help?

I planned to further port AGL along with other guest.

Thanks & Regards,
Nadeem Athani

**Comment by avpatel** [comment]
We have added reference DTS for R-Car H3 Salvator X board. This will help you create DTS for R-Car H3 Starter Kit.
(Refer, arch/arm/board/generic/dts/renesas)

For steps on R-Car H3, it will be similar to ZynqMP board.
(Refer, docs/arm/zynqmp-zcu102.txt)

Once you have Xvisor booting on R-Car H3 Starter Kit, please add documentation under docs/arm

Regards,
Anup
