### ISSUE TITLE
Which compiler?

### ISSUE THREAD

**Issue by anmolsahoo25** [xvisor/xvisor#114]
Hey, 

Since it is not possible to open issues on forks, could someone tell me which `risc-v` toolchain is required to build the hypervisor for `risc-v`. 

I have tried both `riscv-none-embed-gcc-8.2` from GNU MCU Eclipse and `riscv-tools` from github. 

Would be great if you could help me out on this, @avpatel !

**Comment by avpatel** [comment]
You can use toolchain from bootlin for RISC-V 64bit

Refer,
https://toolchains.bootlin.com/

Regards

**Comment by anmolsahoo25** [comment]
Hey! Thanks.That did the trick. Don't know why the other compilers were not working. Should investigate. 

Also, enabling the option `Hypervisor Options/Virtual Serial Port Framework`, is necessary, otherwise the compile fails. Would you suggest somewhere I can make a change, e.g. in the README or a separate README_RISCV.md file? I can put in a pull request, if required.

**Comment by avpatel** [comment]
The generic-64b-defconfig should work for you. All required options are enabled in this defconfig.

Can you provide your steps and error message here?

**Comment by anmolsahoo25** [comment]
Oh. Sorry for bothering you with this. Had overlooked the defconfig option! My bad. This issue can be closed.
