### ISSUE TITLE
USB device access usecase on Raspberry Pi3

### ISSUE THREAD

**Issue by nadeemathani** [xvisor/xvisor#115]
Hello,
After booting with linux guest with USB, SCSI configuration, I am not seeing the directories /sda getting created in /dev after usb pendrive is inserted.
I need to read the usb pendrive contents.
Requesting to provide any advice, suggestions.

Thanks,
Nadeem

**Comment by avpatel** [comment]
Hi,

Before starting the guest using "guest kick" command, use "vdisk" command to attach host block device to guestX/virtio-blk0.

Start the guest after attaching guest vdisk and you will see /dev/sda devices in Guest Linux.

Regards,
Anup

**Comment by nadeemathani** [comment]
Thanks alot!
This is working now.

Regards,
Nadeem
