### ISSUE TITLE
Lilliput(HDMI)display access use cases  on rpi3board 

### ISSUE THREAD

**Issue by pooja-code** [xvisor/xvisor#116]
Hello, 
After booting with linux guest, for binding display using vscreen command require framebuffer list(fb),but it showing empty list. 
Requesting to provide any advice, suggestions

Thanks 
Pooja

**Comment by avpatel** [comment]
Are you trying latest Xvisor-next tree ?

Regards,
Anup

**Comment by pooja-code** [comment]
I am using xvisor 0.2.11 version.

**Comment by avpatel** [comment]
The framebuffer driver for RPi3 was recently merged (few months back). It is not part of released Xvisor.

Try Xvisor staging repo:
https://github.com/avpatel/xvisor-next.git

**Comment by pooja-code** [comment]
Thanks anup,
  Fb node is created successfully.
 While displaying image on lilliput (HDMI) display through fbsplash , I am
getting following error
"Fbsplash : bad PPM file 'filename' "

Could you please give any suggestion to display image.

**Comment by pooja-code** [comment]
Hello
     After cross-compiling helloworld. C file on ubuntu machine these
binary is not working on xvisor's guest
Showing /bin/sh: not found

Could please suggest.

**Comment by avpatel** [comment]
Can you share your cross compilation command?

It could be some trivial issue.

Regards,
Anup

**Comment by pooja-code** [comment]
Hello,

Cross compile on ubuntu machine. That Executable is not executing on xvisor
(linux).

**Comment by avpatel** [comment]
Okay, try using "-static" option of GCC when compiling your hello world.

**Comment by avpatel** [comment]
On RPi3, the host framebuffer is fixed so we cannot do "vdisplay hard_bind" instead we have to do "vdisplay soft_bind". We have as simple implementation of "vdisplay soft_bind" which we will send-out soon. Without a working "vdisplay soft_bind" command, you won't be able to see guest screen on RPi3.

My apologies for inconvenience.

**Comment by avpatel** [comment]
We have got soft bind working on RPi3. We are able see Guest frame buffer on RPi3 screen.

I will send out patches soon.

Regards,
Anup

**Comment by pooja-code** [comment]
Great to hear that from you. Thank you for the update. Kindly, let me know
once the patch is ready.

Thanks & Regards
Pooja.

**Comment by avpatel** [comment]
I have sent patches for implementing vscreen soft_bind 

These patches are tested on Foundation v8 model and I am sure it will work on RPi3. 

Make sure you try it with virt-v8 or virt-v7 guest on RPi3.

Also, refresh rate of 10/15 per second should be good on RPi3.

Regards,
Anup

**Comment by pooja-code** [comment]
Hello
    Thanks for updating display patch.
After applying patch and binding display through soft bind  getting
following logs.
and binary is working fine it is opening framebuffer but on display there
is nothing.

XVisor# vdisk attach guest0/virtio-blk0 usbdisk0
XVisor# vscreen soft_bind guest0 15 fb0 guest0/simplefb
Guest name      : guest0
Refresh rate    : 15 per-second
Escape Keys     : ESC+X+Q
Frame buffer    : fb0
Virtual display : guest0/simplefb
Virtual keyboard: ---
Virtual mouse   : ---
XVisor# vscreen_soft_refresh: not available

 Kindly please suggest.

  Thanks & Regards
   Pooja


>

**Comment by avpatel** [comment]
Hi,

Please try on latest Xvisor-next tree.
https://github.com/avpatel/xvisor-next.git

Regards,
Anup

**Comment by pooja-code** [comment]
Hello
   Thanks anup display is binding successfully and
I can display image using fbsplash.

  I am very new in this domain so i want to know how the soft bind command
is working. And
How the xvsior's accesing peripheral?
Could you please give any guideline so it would more helpful for me to
explore on xvisor .

Thanks and regards
Pooja.
