### ISSUE TITLE
Port xvisor to new platform

### ISSUE THREAD

**Issue by Gopal-Rathod** [xvisor/xvisor#119]
Hi,
We have xvisor support for R-Car H2 legar board.
I have R-Car H3 (starter kit). What are changes need to port xvisor on R-Car H3 (starter kit). 

Please give me any suggestion 

Thanks&Regards,
Gopal

**Comment by pooja-code** [comment]
Hello guys, 

Is there any support to port xvisor on rpi4 (bcm2711) . 

Could you please suggest. 

Thanks & regards 
Pooja

**Comment by bhargavshah1988** [comment]
Hi Pooja,
Support to RPI4 is under development.
Basic prot xvisor will be ready by 2019 December end.
Full fledged support will be ready by mid next year.

Thanks
Bhargav

**Comment by JeWe37** [comment]
Hi,
I would just like to ask how the progress is on Pi4 compatibility, given that it s now "mid next year".
Rgds
JeWe37

**Comment by avpatel** [comment]
Initial bring-up on Xvisor on RPi4 is done. We can now boot and create Guest/VM on RPi4.

Refer, docs/arm directory of latest xvisor-next repo.

Regards,
Anup
