### ISSUE TITLE
How to run multiple guests?

### ISSUE THREAD

**Issue by ALLap97** [xvisor/xvisor#126]
I ran Xvisor for Vexpress-A9 emulated by QEMU  successfully according to the guidance in Vexpress-A9.txt.
but there is only one guest .

![image](https://user-images.githubusercontent.com/33630431/95312675-c2adbe80-087e-11eb-8452-7a69fa9aa2bb.png)

How to run multiple guests in xvisor? How to create another guest?
Do I need to modify the parameter settings in the make process？

**Comment by avpatel** [comment]
Use 	tests/arm32/vexpress-a9/xscript/two_guest_vexpress-a9.xscript instead of tests/arm32/vexpress-a9/xscript/one_guest_vexpress-a9.xscript in step13 of Vexpress-A9.txt

If you need more than two guests then create your own xscript.

Regards,
Anup

**Comment by ALLap97** [comment]
It works.
Thank a lot.
