### ISSUE TITLE
Compilation Issue

### ISSUE THREAD

**Issue by prevotet** [xvisor/xvisor#142]
Hi 
I'am trying to compile Xvisor for RISC-V.

when I follow the compilation steps i.e

CROSS_COMPILE=riscv64-unknown-linux-gnu-
make ARCH=riscv generic-64b-defconfig
make

I have the following error :
```
xvisor/libs/include/libs/bitops.h:519: Error: unrecognized opcode `csrrc s9,0x100,2'
/home/jc/Work/xvisor/libs/include/libs/bitops.h:521: Error: unrecognized opcode `csrs 0x100,a5'
````
version of gcc is 11.1.0
any idea ?
Thank you

**Comment by avpatel** [comment]
Ahh, this the latest Binutils 2.38 compilation issue.

I will fix it Xvisor soon. The patches will be first available in Xvisor-next repo (https://github.com/avpatel/xvisor-next)

**Comment by prevotet** [comment]
That would be great thank you !

**Comment by avpatel** [comment]
This has been fixed in my xvisor-next repo
