### ISSUE TITLE
Faild to run multiple guests on riscv64

### ISSUE THREAD

**Issue by bathtub-01** [xvisor/xvisor#148]
Hi, I'm using the latest version of xvisor-next.
I followed the guide in `test/riscv/virt64/basic/README` and I successfully bring up xvisor for riscv64 on qemu, which creates a single guest in the system.
But it fails when I tried the `two_guest_virt64.xscript` in `test/riscv/virt64/xscript/`, hoping to create multiple guests:

![图片](https://user-images.githubusercontent.com/77145973/194516785-55a20ed2-efcb-4b79-92ff-e8ad84b6aa33.png)

The error message is:
```
region_add: Failed to alloc host RAM for guest1/mem0
guest1: Failed to create
Error: command guest failed (code -1)
line16: failed (error -1)
```
Is there a bug? Or did I miss something? I've emptied the  `build/` folder before my second attempt, so there may not be any building issues.
Thanks for your attention.

**Comment by avpatel** [comment]
Increase the amount RAM provided to Xvisor by changing "-m 512M" to "-m 1G"

**Comment by bathtub-01** [comment]
> Increase the amount RAM provided to Xvisor by changing "-m 512M" to "-m 1G"

Thank you! It works for me. But may I ask why such huge RAM is needed for Xvisor? It doesn't seem realistic for most of embedded devices. Is it because of alignment or something like that?

**Comment by avpatel** [comment]
You can reduce the RAM requirement by adjusting the memory allotted to each Guest. To change guest RAM size, edit "mem0,physical_size" in the two_guest_virt64.xscript.

**Comment by bathtub-01** [comment]
Thanks! It make sense now.

**Comment by FrancoAuri96** [comment]
What is the command to return from a guest to Xvisor main terminal?

**Comment by FrancoAuri96** [comment]
Thank you Anup
