### ISSUE TITLE
d2c.py not found

### ISSUE THREAD

**Issue by Authey** [xvisor/xvisor#153]
Hi,

I had an error when compiling with `make` command

![1](https://user-images.githubusercontent.com/55642617/218827067-06c6b2fc-98a2-48c1-ac38-2fb3f4ec137a.png)

I wonder why this error occurred, should I install some dependencies? Btw, I followed the README instruction in [tests/arm32/virt-v7/linux](https://github.com/xvisor/xvisor/tree/master/tests/arm32/virt-v7/linux) folder, but stuck in step 4 due to this error.

Thanks

**Comment by avpatel** [comment]
Yes, there is a dependency on host python3 (or higher)

Please install python3 (or higher) on your build system

**Comment by Authey** [comment]
Thank you, but I am sure that I have installed python3, is the d2c.py compiled by `python3` command or `python` command since only `python3` works on my machine?

**Comment by Authey** [comment]
Hi, I can `make` Xvisor correctly after I installed `python-is-python3` package, it uses `python` command as `python3`, then the compile process can be done, I will close this issue, thank you a lot.
