### ISSUE TITLE
Unrecognized argument in option '-mabi=aapcs-linux'

### ISSUE THREAD

**Issue by Authey** [xvisor/xvisor#154]
Hi,

When I build Linux, some errors are raised.  
![1](https://user-images.githubusercontent.com/55642617/219867814-431c98b6-992d-4e95-88f2-b03c7dc36d85.png)
Do I need to install any dependencies or run the command with other parameters? Thanks.

Tianyi

**Comment by avpatel** [comment]
Can you share the GCC version you are using "${CROSS_COMPILE}gcc -v" ?

Regards,
Anup

**Comment by Authey** [comment]
Oh, I understood what caused that, so I need to make sure the `CROSS_COMPILE` environment is `arm-none-linux-gnueabihf-`, right? Then it can be built successfully, thank you.

**Comment by avpatel** [comment]
Yes, CROSS_COMPILE environment variable needs to be set

**Comment by Authey** [comment]
Thank you, I can build the Linux kernel now, I'll close this issue.
