### ISSUE TITLE
How to connect to the guest(linux) via ssh

### ISSUE THREAD

**Issue by auking45** [xvisor/xvisor#158]
Hi, I'm using `xvisor` to see the feasibility for our project on RISC-V. Thanks to your great guidance documentation, I have successfully run a guest linux on xvisor for riscv64. Apart from that, I'd like to connect to the guest linux via ssh(scp) to easily copy files from host machine to the guest. I used below command for it, but failed to connect to the guest.
```
qemu-system-riscv64 \
	-machine virt
        -cpu rv64
        -m 2G
        -smp 1
        -nographic
        -kernel ${IMAGE_DIR}/vmm.bin
        -initrd ${IMAGE_DIR}/disk.img
        -append 'vmm.bootcmd="vfs mount initrd /;vfs run /boot.xscript;vfs cat /system/banner.txt"'
        -netdev user,id=net0,hostfwd=tcp::5555-:22
        -device virtio-net-device,netdev=net0
        -device virtio-rng-pci
``` 

I was able to connect to the same linux via ssh without `xvisor`. I think I need to set something in `xvisor` for virtio networking. I'd appreciate it if you could give me a guidance for this. :smile: :pray:

**Comment by avpatel** [comment]
We don't have the VirtIO net driver under drivers/net directory. Once that is available, ssh will work for Guest.

Regards,
Anup

**Comment by auking45** [comment]
Oh. I see. Thank you for the quick reply. I should have searched for the source codes first. Can I ask you if you have a plan for VirtIO net driver implementation?

**Comment by avpatel** [comment]
I certainly want to have a virtio-net driver but I don't have bandwidth in the next few months. 

I would be quite happy if someone else can add the driver.

Regards,
Anup

**Comment by auking45** [comment]
I won't have enough time for this but I wish I could contribute to this task. :sweat_smile: Thank you for your sincere reply. I will close this issue.

Regards,
Jinha
