### ISSUE TITLE
How to set up network connection between the host(linux) and the guest(linux in xvisor)?

### ISSUE THREAD

**Issue by chinochan2001** [xvisor/xvisor#166]
Hi,
I'm using qemu instead of [foundation model](https://github.com/xvisor/xvisor/blob/master/docs/arm/foundation-v8.txt) to run aarch64 linux in xvisor. The current command I use is 
`qemu-system-aarch64 -nographic -M virt,virtualization=on,gic-version=2 -cpu cortex-a72 -m 4G -kernel ./build/vmm.bin -initrd ./build/disk.img -append 'vmm.bootcmd="vfs mount initrd /;vfs run /boot.xscript;vfs cat /system/banner.txt"'`.

I have no idea what I should do to set up the network connection between the host linux system and the guest linux system inside xvisor.  I didn't find a tutorial in this repository. 

Can you give me some instructions?
Thank you.

**Comment by avpatel** [comment]
What is host Linux here?
Is it Linux running on other Xvisor Guest ?

**Comment by chinochan2001** [comment]
Just means the Linux that runs the qemu.

**Comment by avpatel** [comment]
For this, we need to get the VirtIO network driver working on Xvisor which will allow Xvisor guests to access the host network via virtual network switch.

**Comment by chinochan2001** [comment]
Thanks. Can two guests communicate with each other?

**Comment by avpatel** [comment]
Yes, we have VirtIO network available inside Guest and multiple Guests can communicate with each other.

To try, just assign someone private IP to eth0 on each Guest and ping each other.

**Comment by chinochan2001** [comment]
Thank you for your reply. I'll close this issue.
