### ISSUE TITLE
How to make guest Linux see block devices?

### ISSUE THREAD

**Issue by lsc2001** [xvisor/xvisor#168]
Hi,
I have made an addtional disk image `fs.img` and add
 `-drive file=fs.img,if=none,id=drive0 -device virtio-blk-device,drive=drive0,id=virtioblk0` options to qemu. I can see and mount it in xvisor, but I dont' know how to make guest Linux see it. I can't find it under `/dev`.
![image](https://github.com/xvisor/xvisor/assets/20860814/2f6ea1e4-1814-444d-8f7a-b5b8fb9dde5c)
Could you give me some instructions?

Thanks.

**Comment by lsc2001** [comment]
Got it. Attach vda to guest0/virtio-blk0 can solve this problem.
I'll close this issue.

**Comment by LilDuan** [comment]
hi，请问你的fs.img文件是在哪里创建的呢，我想尝试和你同样的操作。在创建完img后怎么挂载在xvisor的blockdev的设备列表下呢？谢谢！

**Comment by LilDuan** [comment]
> Got it. Attach vda to guest0/virtio-blk0 can solve this problem. I'll close this issue.

hi, 这之后你尝试过如何在Guest linux内创建块设备并与 guest0/virtio-blk0 关联吗，我想知道怎么在linux中实际管理这里创建的vda设备
