### ISSUE TITLE
run linux in xvisor

### ISSUE THREAD

**Issue by Gao-xt** [xvisor/xvisor#179]
Hi,I encountered the following issue when attempting to run Linux on XVisor:

XVisor# guest kick guest0
guest0: Kicked
XVisor# cpu_vcpu_stage2_map: guest_phys=0x000127170AA04000 size=0x4096 map failed
do_error: CPU0: VCPU=guest0/vcpu0 page fault failed (error -1)
           zero=0x0000000000000000          ra=0x0000000000000000
             sp=0x0000000000000000          gp=0x0000000000000000
             tp=0x0000000000000000          s0=0x0000000000000000
             s1=0x0000000000000000          a0=0x0000000000000000
             a1=0x0000000000000000          a2=0x0000000000000000
             a3=0x0000000000000000          a4=0x000127170AA04C63
             a5=0x0000000000000000          a6=0x0000000000000000
             a7=0x000127170AA04C63          s2=0x0000000000000000
             s3=0x0000000000000000          s4=0x0000000000000000
             s5=0x0000000000000000          s6=0x0000000000000000
             s7=0x0000000000000000          s8=0x0000000000000000
             s9=0x0000000000000000         s10=0x0000000000000000
            s11=0x0000000000000000          t0=0x0000000000000000
             t1=0x0000000000000000          t2=0x0000000000000000
             t3=0x0000000000000000          t4=0x0000000000000000
             t5=0x0000000000000000          t6=0x0000000000000000
           sepc=0x0000000000000026     sstatus=0x0000000200004120
        hstatus=0x00000002002001C0     sp_exec=0x0000000010A41000
         scause=0x0000000000000017       stval=0x000127170AA04C63
          htval=0x000049C5C2A81318      htinst=0x0000000001103023

When I mount "disk.img," I identified the issue  in "build/tests/riscv/virt64/basic/firmware.bin." How can I resolve the compilation error for "firmware.bin"?

--ubuntu22.04
--met the same issue in both xvisor and xvisor-next
--qemu latest

**Comment by Gao-xt** [comment]
I rebuilt the disk.img using another firmware.bin generated in a CentOS environment, and didn't encounter this issue. Subsequently, following the solution provided by **https://github.com/xvisor/xvisor/issues/175**, I upgraded Ubuntu to 23.04 and riscv64-unknown-linux-gnu-gcc to version 12. However, when compiling both Xvisor and Xvisor again, the following issue arose:

Assembler messages:
Fatal error: -march=rv64imafdc_zicsr_zifencei: Invalid or unknown z ISA extension: 'zifencei'
make: *** [Makefile:430: /home/armin/workspace-xvisor/xvisor-next/build/arch/riscv/cpu/generic/cpu_entry.o] Error 1

**Comment by avpatel** [comment]
Are you trying late Xvisor repo ?

**Comment by Gao-xt** [comment]
It's peculiar that I remake the toolchain then somehow it works.：）
Thank you for your time and patience.
