### ISSUE TITLE
Are ARM multi-core architectures supported?

### ISSUE THREAD

**Issue by sradhakrishna** [xvisor/xvisor#98]
Hi,

Just wanted to check if one can emulate ARM multi-core (symmetric and asymmetric) systems using xvisor?

Please let me know.

Regards,
Radha.

**Comment by avpatel** [comment]
Hi Radha,

We provide both ARM multi-core symmetric/asymmetric system to Guest/VM.
In other words, VCPUs of the same Xvisor Guest can get different amount of CPU time by varying the VCPU timeslice. By default all VCPUs in Xvisor get same timeslice.

It would good if you can post further queries to xvisor-devel[at]googlegroups[dot]com

Regards,
Anup
